import { Nav } from './Components/layout/nav/nav'
import './globals.css'
import { Inter } from 'next/font/google'
import { RootFolderDto } from './drive/[folderId]/components/folders'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
async function getMobileMenus() :Promise<RootFolderDto>{
  const res = await fetch(
    `https://script.google.com/macros/s/AKfycbxdwTbGYbK1Ku-KG0jgaByox6XfzOauc3dSJoGwVUO78HBHQ9FaQzDqTJsgwE4cdQES-w/exec?folderId=1S0xfEFx6JRZj1ldN2won-SpXZC7QBQ17`,
    { next: { revalidate: 360 } }
    );
  if (!res.ok) {
    throw new Error('Failed to fetch data');
  }
  return res.json();
}
export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const menus = await getMobileMenus()
  return (
    <html lang="en">
      <body className={inter.className}><section>
        <div className="min-h-full">
        <Nav menus={menus.folders}/>
			<main>
				<div className="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
          { children }
				</div>
			</main>
			</div>
      </section></body>
    </html>
  )
}
